# Generated by Django 2.1.8 on 2019-05-06 14:42

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('pagination_key', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.TextField(blank=True)),
                ('required', models.BooleanField()),
                ('sql_required', models.BooleanField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', related_query_name='parameter', to='api.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', jsonfield.fields.JSONField()),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_selects', related_query_name='endpoint_select', to='api.Endpoint')),
                ('select_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent', related_query_name='dependent', to='api.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_file_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', related_query_name='schema', to='api.Endpoint')),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Query'),
        ),
        migrations.AlterUniqueTogether(
            name='endpointparameter',
            unique_together={('endpoint', 'name')},
        ),
    ]
