# Generated by Django 2.1.8 on 2019-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointparameter',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
