# Generated by Django 2.1.8 on 2019-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_endpointparameter_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointselect',
            name='select_to_field_name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
