# Generated by Django 2.1.8 on 2019-05-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_endpointparameter_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='schemadescription',
            name='endpoint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', related_query_name='schemas', to='api.Endpoint'),
        ),
        migrations.AddField(
            model_name='schemaentry',
            name='schema_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entry', to='api.SchemaDescription'),
        ),
    ]
