# Generated by Django 2.1.8 on 2019-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_endpointparameter_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemadescription',
            name='level',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='schemadescription',
            name='name',
            field=models.CharField(default='kek', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemadescription',
            name='type',
            field=models.CharField(default='kek', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schemadescription',
            name='value',
            field=models.CharField(default='kek', max_length=255),
            preserve_default=False,
        ),
    ]
