# Generated by Django 2.1.8 on 2019-05-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_schema_description_adds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemaentry',
            old_name='schema_name',
            new_name='schema',
        ),
        migrations.AddField(
            model_name='schemaentry',
            name='entry_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Select', 'Select'), ('Db', 'Db'), ('Nested', 'Nested')], max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemaentry',
            name='level',
            field=models.PositiveSmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemaentry',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schemaentry',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
